### ISSUE TITLE
Inclusive/Exclusive behavior for join conditions

### ISSUE THREAD

**Issue by wylbee** [bcodell/dbt-activity-schema#66] opened 2024-04-17 16:15 UTC
@bcodell Great work on the package!

I have multiple activities that have an identical timestamp, which is accurate to the business process they represent. Right now the `after`, `before`, and `between` join conditions are all strictly exclusive, which means that I cannot query the relationships between these activities as I would want.  Particularly for the `between` join, I would have expected an implementation that was either fully inclusive given the way that term [typically behaves in SQL](https://docs.getdbt.com/sql-reference/between) or inclusive of start and exclusive of end based on what I typically do in practice to get mutually exclusive collectively exhaustive behavior. I can confirm that the macros behave as expected when I change the </> to <=/>= in the `macros/activity_schema/dataset/joins/_join_clauses.sql` file.

Am I missing a way to get the desired behavior? Else I'd rather not tweak my underlying data (like say aging certain activities by a ms) or maintain a fork, and would be happy to contribute a PR to get the desired result if I can get some direction on how you'd prefer to go about it. Some approaches that come to mind are:

1. Edit `after` and `before` to be inclusive. Adjust `between` to be inclusive start and maintain the existing exclusive end.
2. Add new join conditions with new names to reflect option 1. Something like `after_inclusive` or `between_inclusive_start_exclusive_end`
3. Add a new condition to the AQL syntax to allow for inclusive/exclusive specification per option 1. 
4. Something else.

Assuming the current behavior is intentional, option 1 would be no go & a breaking change. Option 2 & 3 could be implemented such that the default behavior does not change and all new functionality is additive. Option 2 is less elegant but likely easier to implement.

**Comment by bcodell** [comment] 2024-04-18 02:29
Hey @wylbee - great to hear from you!

Great question - the implemented behavior is in line with the official Activity Schema spec (see the example query [here](https://github.com/ActivitySchema/ActivitySchema/blob/main/2.0.md#multiple-activities) for reference - it's very subtle), which was the initial guideline for this package. In other words, the current implementation is indeed a feature and not a bug. The impetus for this design comes from a couple places - one, from the simplifying assumption that a given entity can only take one action at a time, and more tactically in the case of joining a given activity to itself in any case of `after`, `before`, and `between`, where an inclusive timestamp evaluation for joins like "last before" and "first after" would effectively result in an activity occurrence joining to itself, which is definitely the wrong behavior.

But your point about the divergence in functionality between SQL's native `between` operator and the Activity Schema spec is certainly confusing, the Activity Schema spec certainly has room for evolution, and I'm generally always open to adding new functionality to the project, given the right use case and implementation. Regarding your suggestions, my preliminary instinct is to err closer to option 1 - namely keep the query behavior consistent (i.e. _always_ inclusive or _always_ exclusive) across join conditions within a given project for sake of reliability and simplicity, and giving the developer the ability to decide which implementation they'd prefer. I definitely _don't_ want to support a case where the inclusivity is conditional (e.g. when the primary activity is joining to itself). I'm also hesitant to expand the join conditions (and subsequently the AQL syntax) without really understanding the use cases more thoroughly, as that approach introduces more complexity to the framework.

In light of that last point, are you able to share more context about the use cases you have that require joining distinct activities with identical timestamps? Any details about the business processes and the key activities/steps being measured would be especially helpful in figuring out the right path forward here.

**Comment by wylbee** [comment] 2024-04-18 14:07
@bcodell Thanks for the response, all makes sense to me! I missed the load-bearing assumption in the spec that activities cannot share a timestamp/entities are only taking one action at a time, and I've been handling the complexity you're referring to in your first full paragraph manually when querying my streams. Open to the feedback that I may need a refactor of my activities over a change to this project if that seems appropriate.

Stepping back, the issue I'm running into is that the current state implementations of `after`, `before`, and `between` result in unqueryable/incorrect relationships between activities if a timestamp is shared, which produces datasets that are not MECE where I would expect them to be. What I'm primarily trying to achieve is MECE behavior, which in practice means that in addition to the `after`, `before`, and `between` implementations I am also using joins that map to `on_or_after` and `between_on_or_after`/`on_or_after_and_before`.   There are four places in my current project where this crops up:

1. When activities happen at the same timestamp for the given entity per the operational source system. 
2. When the operational source system does not record full timestamp grain precision (i.e. records a date rather than a timestamp).
3. When using an existing activity to build another activity or role-playing an activity between more than one stream (especially when the entity is not a customer + encompasses many customers).
4. When I'm building activities using an ELT based timestamp like `ingested_at` because an appropriate one does not exist in the operational source system. 

It seems like the way Narrator recommends dealing with option 3 (and I would assume options 2 & 4) is to [age the timestamp](https://docs.narrator.ai/docs/create-an-activity-using-another-activity) so that none of the timestamps line up. This approach seems brittle and involves making some data less accurate vs. the source system in a way that should be practically fine but is a theoretical red flag. I think with the right dbt tests in place this could be done in a way that is mechanically responsible, though my theoretical discomfort with the approach remains.

For use cases, an example from a loan servicing business is:

- At X days delinquent, a loan is charged off. Loans can also be charged off for a variety of other reasons.
- In the operational source system, a delinquency charge off is automatic and the timestamps are identical (aka the ts of the delinquency accrual to X = the ts of the charge off).
- I have two activities- `accrues_balance` (effectively a snapshot of the state of the loan at midnight, including delinquency) and `charges_off`.
- Attempting to use `accrues_balance` as the primary and do a `between` join for `charge_off` never joins the charge off if it is a delinquency charge off since the timestamp is shared with the primary activity.

Based on your thoughts on the package, the two options jumping out to me are:

1. Refactor my project so that activities reflect the simplifying assumption that entities only take one action at a time. Use defensive dbt tests to ensure that this is true in practice + catch data that needs to be adjusted so that it doesn't invisibly drop out of AQL queries.
2. Add additional temporal joins for `on_or_after` and `between_on_or_after` while leaving the default functionality the same. This would also allow for [other temporal joins to be added in the future](https://github.com/ActivitySchema/ActivitySchema/issues/13) at the cost of evolving the spec and added complexity.

I'm hesitant to evolve the spec in a vacuum and don't have a ton of confidence that the maintainers are responding to feedback on the main repo. I do see space to expand the temporal joins, but unless you're seeing something different I'm inclined to attempt the refactor of option 1 and see how that goes before pushing for spec changes that would drive changes to this project. Based on that context, where is your head at with this one?

**Comment by bcodell** [comment] 2024-04-18 20:10
@wylbee Thanks for the added context! I agree that evolving the spec here is probably the wrong path. (Aside - I've been contemplating a more generalized event modeling/querying solution, in which activity schema is simply one of many event modeling frameworks a developer can choose - also supporting other event modeling approaches including ones that have more robust MECE support - but will save that discussion for a separate forum.) As such, I'd rather start with exploring alternative modeling methods (your option 1) for the use case at hand as opposed to broadening the functionality of this package (your option 2).

On that note, I'll focus more generally on the output you're trying to produce (so as not to get too deep in the weeds in a domain where I lack familiarity). It sounds like the output you're trying to achieve is a dataset with 1 row per loan per "active" day of the loan with columns for the loan balance accrued on that day and an indicator of whether or not the loan was charged off on the given day. Is that correct?

If so, the difficulty I see here is that the telemetric nature of the `accrues_balance` activity is being (understandably) conflated with the date spine-like structure of a separate `has_active_day` activity. I've used the following approach for similar activity dynamics in different domains:
* create a synthetic `has_active_day` activity for the entity in question (presumably loans in this case), where I derive the start date and end date for each entity with SQL logic, and assert the time for each activity occurrence to be midnight.
* ensure no timestamps in other activities have a timestamp at midnight - currently I manually add a microsecond in sql if I identify a timestamp at midnight
* adjust the activity definition logic for telemetry-based activities (e.g. `accrues_balance`) to only include occurrences when the measured attribute changes in a way that's notable to the business
* build the aforementioned dataset with the `has_active_day` activity as the primary, then append/aggregate other activities as needed

In the event that I've totally missed the mark here, I do agree that an arbitrary time offset (i.e. Narrator's recommendation and my current implementation in my own projects) is a fairly brittle solution, and where possible I try to rethink the timestamp logic of the activities themselves in the context of their use cases for the business before pursuing the arbitrary offset approach. So, for example, maybe the timestamp of the `accrues_balance` activity should be the timestamp at which each loan was created/originated + n days since origination (you may already be doing this - going based off the "snapshot at midnight" comment). Anyway, let me know if my proposed approach makes sense (or if I'm entirely off base 😅).

**Comment by brittmdavis1** [comment] 2024-04-18 21:37
Hey @wylbee + @bcodell - happy to add context from my personal experience (I used to work at Narrator and have implemented the activity schema for many many companies). The issue of two activities with the same timestamp is an edge case that breaks the assumptions of the existing activity schema spec. In practice, what I've found is that these scenarios are typically very rare because the activity schema is typically used to analyze behavioral activity from some user /agent, and in practice it's very unnatural for two events to occur at exactly the same timestamp down to the ms. It's only in cases where behavior is manufactured (ie. daily snapshot) or when the timestamps are not captured with sufficient granularity. 

In cases of manufactured data (daily snapshot), I adjust timestamps to ensure uniqueness is maintained, same thing for timestamps without sufficient granularity. This has always been enough for our use cases.

**Comment by wylbee** [comment] 2024-04-19 01:13
Thanks for the input @bcodell & @brittmdavis1, extremely helpful!

@bcodell think we're aligned on approach 1, and feel good about pursuing that option. Good to close this issue as a result.

Appreciate the partnership on use case- you've got the read on the desired end state directionally right and the solution you sketched is pretty close to what I drew up as well. This particular edge case is pretty anomalous compared to other business models and industries I've worked with- the root system/business/contractual behavior reflects a number of simultaneous activities (like incrementing days past due and accruing daily interest) firing at midnight every day for all active accounts in the loan portfolio. In practice it ends up looking like a date spine and the row count for the models you sketch in your first and third bullets end up being identical, but the offset you describe in bullet two should get everything working as expected. I'm in the middle of a system migration that allows me some room to refactor, so will try a few approaches including this one and run with whatever works best!

@brittmdavis1 super appreciative to get your perspective and the confirmation that your extensive experience supports this edge case being extremely rare, usually due to manufactured/insufficiently granular data, and practically solvable with timestamp adjustment. At this juncture I feel pretty comfortable proceeding with that approach while using dbt tests to ensure that the core assumption around unique timestamps is met. Thank you!

**Comment by bcodell** [comment] 2024-04-19 13:55
Thanks for the expert opinion @brittmdavis1! Helpful to have confirmation based on your implementation experiences.

To recap: identical timestamps typically relate to manufactured activities and activities without sufficient timestamp granularity, and in practice, organically created behavioral data effectively never has the exact same timestamp down to the microsecond for a given user/agent.

@wylbee I'll close this issue per your comment. Thanks again for opening it! Will hopefully serve as a helpful reference for other users.

**Closed as completed** 2024-04-19 14:49 UTC
